version '1.0.0'


client_scripts {
	'@es_extended/locale.lua',
	'locales/fr.lua',
	'config.lua',
	'client.lua'
}

ui_page 'html/ui.html'

files {
    'html/menu.html',
	'html/Berlines.html',
	'html/Bikers.html',
	'html/camionnettes.html',
	'html/compactes.html',
	'html/couper.html',
	'html/Cross.html',
	'html/grossescylindrer.html',
	'html/Scooters.html',
	'html/sportives.html',
	'html/sportivesclassiques',
	'html/supersportives.html',
	'html/SUV.html',
	'html/toutterrains.html',
	'html/img/cursor.png',
    'html/app.css',
    'html/scripts/app.js'
}

img {
	'background/background.jpg',
	'background/background1.jpg',
	'image berlines/asea.jpg',
	'image berlines/asterope.jpg',
	'image berlines/cog55.jpg',
	'image berlines/cog552.jpg',
	'image berlines/cognoscenti.jpg',
	'image berlines/cognoscenti2.jpg',
	'image berlines/emperor.jpg',
	'image berlines/emperor2.jpg',
	'image berlines/fugitive.jpg',
	'image berlines/glendale.jpg',
	'image berlines/ingot.jpg',
	'image berlines/intruder.jpg',
	'image berlines/limo2.jpg',
	'image berlines/premier.jpg',
	'image berlines/primo.jpg',
	'image berlines/primo-custom.jpg',
	'image berlines/regina.jpg',
	'image berlines/schafter.jpg',
	'image berlines/schafter5.jpg',
	'image berlines/schafter6.jpg',
	'image berlines/stafford.jpg',
	'image berlines/stanier.jpg',
	'image berlines/stratum.jpg',
	'image berlines/stretch.jpg',
	'image berlines/super-diamond.jpg',
	'image berlines/surge.jpg',
	'image berlines/tailgater.jpg',
	'image berlines/warrener.jpg',
	'image berlines/washington.jpg',
	'image camionnettes/bison.jpg',
	'image camionnettes/bison2.jpg',
	'image camionnettes/bison3.jpg',
	'image camionnettes/bobcat-xl.jpg',
	'image camionnettes/boxville.jpg',
	'image camionnettes/boxville2.jpg',
	'image camionnettes/boxville3.jpg',
	'image camionnettes/boxville4.jpg',
	'image camionnettes/burrito.jpg',
	'image camionnettes/burrito2.jpg',
	'image camionnettes/burrito3.jpg',
	'image camionnettes/burrito4.jpg',
	'image camionnettes/camper.jpg',
	'image camionnettes/clown-van.jpg',
	'image camionnettes/gang-burrito.jpg',
	'image camionnettes/gang-burrito2.jpg',
	'image camionnettes/journey.jpg',
	'image camionnettes/minivan.jpg',
	'image camionnettes/minivan-custom.jpg',
	'image camionnettes/paradise.jpg',
	'image camionnettes/pony.jpg',
	'image camionnettes/pony2.jpg',
	'image camionnettes/rumpo.jpg',
	'image camionnettes/rumpo2.jpg',
	'image camionnettes/rumpo-custom.jpg',
	'image camionnettes/speedo.jpg',
	'image camionnettes/speedo-custom.jpg',
	'image camionnettes/surfer.jpg',
	'image camionnettes/surfer2.jpg',
	'image camionnettes/taco-van.jpg',
	'image camionnettes/youga.jpg',
	'image camionnettes/youga-classic',
	'image carsportives/9f.jpg',
	'image carsportives/9f-cabrio.jpg',
	'image carsportives/alpha.jpg',
	'image carsportives/banshee.jpg',
	'image carsportives/banshee2.jpg',
	'image carsportives/bestiagts.jpg',
	'image carsportives/blista-compact.jpg',
	'image carsportives/blista-monkey.jpg',
	'image carsportives/buffalo.jpg',
	'image carsportives/buffalo2.jpg',
	'image carsportives/buffalo-sprunk.jpg',
	'image carsportives/carbonizzare.jpg',
	'image carsportives/comet.jpg',
	'image carsportives/comet-retro-custom.jpg',
	'image carsportives/comet-safari.jpg',
	'image carsportives/comet-sr.jpg',
	'image carsportives/coquette.jpg',
	'image carsportives/coquette2.jpg',
	'image carsportives/drift-tampa.jpg',
	'image carsportives/elegy-retro-custom.jpg',
	'image carsportives/elegy-rh8.jpg',
	'image carsportives/feltzer.jpg',
	'image carsportives/flash-gt.jpg',
	'image carsportives/furoregt.jpg',
	'image carsportives/fusilade.jpg',
	'image carsportives/futo.jpg',
	'image carsportives/gb200.jpg',
	'image carsportives/hotring-sabre.jpg',
	'image carsportives/itali-gto.jpg',
	'image carsportives/jester.jpg',
	'image carsportives/jester2.jpg',
	'image carsportives/jester-classic.jpg',
	'image carsportives/khamelion.jpg',
	'image carsportives/kuruma.jpg',
	'image carsportives/kuruma2.jpg',
	'image carsportives/lynx.jpg',
	'image carsportives/massacro.jpg',
	'image carsportives/massacro2.jpg',
	'image carsportives/neon.jpg',
	'image carsportives/omnis.jpg',
	'image carsportives/pariah.jpg',
	'image carsportives/penumbra.jpg',
	'image carsportives/raiden.jpg',
	'image carsportives/rapid-gt.jpg',
	'image carsportives/rapid-gt2.jpg',
	'image carsportives/raptor.jpg',
	'image carsportives/revolter.jpg',
	'image carsportives/ruston.jpg',
	'image carsportives/schafter3.jpg',
	'image carsportives/schafter4.jpg',
	'image carsportives/schwartzer.jpg',
	'image carsportives/sentinel-classic',
	'image carsportives/seven70.jpg',
	'image carsportives/specter-custom.jpg',
	'image carsportives/streiter.jpg',
	'image carsportives/sultan.jpg',
	'image carsportives/surano.jpg',
	'image carsportives/tropos.jpg',
	'image carsportives/verlierer.jpg',
	'image carsportives/zr-380.jpg',
	'image compactes/arena-issi.jpg',
	'image compactes/blista.jpg',
	'image compactes/brioso.jpg',
	'image compactes/dilettante.jpg',
	'image compactes/dilettante2.jpg',
	'image compactes/issi.jpg',
	'image compactes/issi-classic.jpg',
	'image compactes/panto.jpg',
	'image compactes/prairie.jpg',
	'image compactes/rhapsody.jpg',
	'image couper/cognoscenti-cabrio.jpg',
	'image couper/exemplar.jpg',
	'image couper/f620.jpg',
	'image couper/felon.jpg',
	'image couper/felon-gt.jpg',
	'image couper/jackal.jpg',
	'image couper/oracle.jpg',
	'image couper/oracle2.jpg',
	'image couper/sentinel.jpg',
	'image couper/sentinel-xs.jpg',
	'image couper/windsor.jpg',
	'image couper/windsor2.jpg',
	'image couper/zion.jpg',
	'image couper/zion-cabrio.jpg',
	'image Grosses cylindrer/arena-dominator.jpg',
	'image Grosses cylindrer/arena-impaler.jpg',
	'image Grosses cylindrer/arena-slamvan.jpg',
	'image Grosses cylindrer/blade.jpg',
	'image Grosses cylindrer/buccaneer.jpg',
	'image Grosses cylindrer/buccaneer-custom.jpg',
	'image Grosses cylindrer/chino.jpg',
	'image Grosses cylindrer/chino-custom.jpg',
	'image Grosses cylindrer/clique.jpg',
	'image Grosses cylindrer/coquette-blackfin.jpg',
	'image Grosses cylindrer/dominator.jpg',
	'image Grosses cylindrer/dominator-gtx.jpg',
	'image Grosses cylindrer/dominator-pisswasser.jpg',
	'image Grosses cylindrer/duke-o-death.jpg',
	'image Grosses cylindrer/dukes.jpg',
	'image Grosses cylindrer/ellie.jpg',
	'image Grosses cylindrer/faction.jpg',
	'image Grosses cylindrer/faction-custom.jpg',
	'image Grosses cylindrer/faction-custom-donk.jpg',
	'image Grosses cylindrer/gauntlet.jpg',
	'image Grosses cylindrer/gauntlet-redwood.jpg',
	'image Grosses cylindrer/hermes.jpg',
	'image Grosses cylindrer/hotknife.jpg',
	'image Grosses cylindrer/hustler.jpg',
	'image Grosses cylindrer/impaler.jpg',
	'image Grosses cylindrer/imperator.jpg',
	'image Grosses cylindrer/lurcher.jpg',
	'image Grosses cylindrer/moonbeam.jpg',
	'image Grosses cylindrer/moonbeam-custom.jpg',
	'image Grosses cylindrer/nightshade.jpg',
	'image Grosses cylindrer/phoenix.jpg',
	'image Grosses cylindrer/picador.jpg',
	'image Grosses cylindrer/rat-loader.jpg',
	'image Grosses cylindrer/rat-truck.jpg',
	'image Grosses cylindrer/ruiner.jpg',
	'image Grosses cylindrer/ruiner-2000.jpg',
	'image Grosses cylindrer/sabre-turbo-custom.jpg',
	'image Grosses cylindrer/sabre-turbo.jpg',
	'image Grosses cylindrer/slamvan.jpg',
	'image Grosses cylindrer/slamvan-custom.jpg',
	'image Grosses cylindrer/stallion.jpg',
	'image Grosses cylindrer/stallion-burger.jpg',
	'image Grosses cylindrer/tampa.jpg',
	'image Grosses cylindrer/vigero.jpg',
	'image Grosses cylindrer/virgo.jpg',
	'image Grosses cylindrer/virgo-classic.jpg',
	'image Grosses cylindrer/virgo-classic-custom.jpg',
	'image Grosses cylindrer/voodoo.jpg',
	'image Grosses cylindrer/voodoo-custom.jpg',
	'image Grosses cylindrer/yosemite.jpg',
	'image moto/akuma.jpg',
	'image moto/avarus.jpg',
	'image moto/bagger.jpg',
	'image moto/bati-801.jpg',
	'image moto/bati-801rr.jpg',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',
	'image moto/',


}
